#!/bin/bash

rustc --edition=2024 --emit=obj -C opt-level=2 --crate-type=lib --target=thumbv6m-none-eabi main.rs
mv main.o main.elf
arm-none-eabi-objdump -Sdrl main.elf > obj
# ~/test7800/test7800 -run main.elf
